[versions]
koin = "3.0.1"
junit = "4.13"
appcompat = "1.7.0"

[libraries]
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
junit = { module = "junit:junit", version.ref = "junit" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
