[versions]
gradle = "8.3.2" # AGP
kotlin-gradle-plugin = "1.9.21" # Kotlin version
koin = "3.0.1"
junit = "4.13.2"
appcompat = "1.7.0"
mockito = "5.0.0"
material = "1.12.0"
test-core = "1.6.1"
roboelectric = "4.10.3"
test-runner = "1.6.2"
retrofit = "2.4.0"
okhttp-interceptor = "4.2.1"
compose = "1.7.8"
compose-theme-adapter = "1.2.1"
play-review = "2.0.2"
navigation = "2.8.9"
junit-ext = "1.2.1"
mockwebserver = "4.2.1"
commons-io = "2.13.0"
constraintlayout = "2.2.1"
viewmodel = "2.2.0"
play-services-maps = "19.2.0"
play-services-location = "21.3.0"
coroutines = "1.8.0"
desugaring = "2.1.5"
arch-core-testing = "2.2.0"
espresso = "3.6.1"
test-rules = "1.6.1"

[libraries]
# Root Gradle
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }

koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
junit = { module = "junit:junit", version.ref = "junit" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ext" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
viewmodel = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "viewmodel" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core-testing" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-rules = { module = "androidx.test:rules", version.ref = "test-rules" }

# Instrumented tests
test-core = { module = "androidx.test:core-ktx", version.ref = "test-core" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }

# Retrofit
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-interceptor" }

# Compose libraries
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "compose-theme-adapter" }

# In-app reviews
play-review-core = { module = "com.google.android.play:review", version.ref = "play-review" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "play-review" }

# Navigation
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

# Play Services
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }


